name = "lokbhasha-api"
main = "src/worker.ts"
compatibility_date = "2026-04-09"

[vars]
CORS_ALLOWED_ORIGINS = "http://localhost:3000"
GLOSSARY_SOURCE_PATH = "dict/19k.json"
GLOSSARY_SOURCE_FORMAT = "english_to_marathi_list"
